#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           4
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config ignore_ewmh_struts false
bspc config top_padding 0
bspc config bottom_padding 0


pkill polybar
~/.config/polybar/launch.sh &
